// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYsmkoyqGS-u0lG9UZx822bTfO2BXoRDQ',
    appId: '1:256802678371:web:288e08e4bc272b14153a56',
    messagingSenderId: '256802678371',
    projectId: 'sehir-bulmaca',
    authDomain: 'sehir-bulmaca.firebaseapp.com',
    storageBucket: 'sehir-bulmaca.firebasestorage.app',
    measurementId: 'G-NWYBMV8NT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE_Tf8D-nwAjG0-7Jfz2eYPclVucPq9IQ',
    appId: '1:256802678371:android:0641833a9be699ee153a56',
    messagingSenderId: '256802678371',
    projectId: 'sehir-bulmaca',
    storageBucket: 'sehir-bulmaca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADk7yvcByGpXYilaDAIek0opLAx4NOWMQ',
    appId: '1:256802678371:ios:cb59957e313063e5153a56',
    messagingSenderId: '256802678371',
    projectId: 'sehir-bulmaca',
    storageBucket: 'sehir-bulmaca.firebasestorage.app',
    iosBundleId: 'com.sametyucel.sehirBulmaca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADk7yvcByGpXYilaDAIek0opLAx4NOWMQ',
    appId: '1:256802678371:ios:cb59957e313063e5153a56',
    messagingSenderId: '256802678371',
    projectId: 'sehir-bulmaca',
    storageBucket: 'sehir-bulmaca.firebasestorage.app',
    iosBundleId: 'com.sametyucel.sehirBulmaca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYsmkoyqGS-u0lG9UZx822bTfO2BXoRDQ',
    appId: '1:256802678371:web:5e01e47abecea58f153a56',
    messagingSenderId: '256802678371',
    projectId: 'sehir-bulmaca',
    authDomain: 'sehir-bulmaca.firebaseapp.com',
    storageBucket: 'sehir-bulmaca.firebasestorage.app',
    measurementId: 'G-C2KTXZ3WXB',
  );
}
